//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Resources;

[assembly:AssemblyCompany ("そんなもんネイ")]
[assembly:AssemblyConfigurationAttribute ("Debug")]
[assembly:AssemblyProduct ("EZSens")]
[assembly:AssemblyVersion ("1.0.1.0")]              // アセンブリバージョン
[assembly:AssemblyFileVersion ("1.0.1.0")]          // ファイルバージョン
[assembly:AssemblyInformationalVersion ("1.0.1.0")] // 製品バージョン
[assembly:AssemblyTitle ("EZSens")]
[assembly:System.Runtime.Versioning.TargetPlatformAttribute ("Windows7.0")]
[assembly:System.Runtime.Versioning.SupportedOSPlatformAttribute ("Windows7.0")]
[assembly:AssemblyDescriptionAttribute ("FPSゲームにおける振り向き距離の計算")]
[assembly:AssemblyCopyright ("")]
[assembly:AssemblyTrademark ("")]
[assembly:AssemblyCulture ("")]
[assembly:ComVisible (false)]
//[assembly: Guid("98BF1A7E-F04F-40F5-9D94-8F71A1B70945")]
[assembly:NeutralResourcesLanguage ("ja-JP")]

// MSBuild WriteCodeFragment クラスによって生成されました。
